export const storeCleaners_1 = [
  {
    id:1,
    title:"Средство для чистки сантехники кислотное AC-GEL",
    price_1_litre:910,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:2,
    title:"Средство для чистки сантехники хлорное CH-GEL",
    price_1_litre:500,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:3,
    title:"Срество для чистки сантехники и отбеливания WH-Gel",
    price_1_litre:630,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:4,
    title:"Жидкое мыло AMELI",
    price_1_litre:300,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:5,
    title:"Жидкое мыло AMELI+ ",
    price_1_litre:340,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:6,
    title:"Жидкое мыло с дезинфецирующим эффектом AMELI DES ",
    price_1_litre:400,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:7,
    title:"Жидкое мыло AMELI GLICERIN",
    price_1_litre:420,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:8,
    title:"Средство для удаления пятен ANTI-GRAFFITI",
    price_1_litre:2100,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:9,
    title:"Средство для удаления жира, пищевых нагаров CARBON",
    price_1_litre:550,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:10,
    title:"Щелочное средтво для очистки текстиля и ковров CARPET",
    price_1_litre:820,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:11,
    title:"Средство для чистки после ремонта CLEANER CEMENT",
    price_1_litre:950,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:12,
    title:"Средство для мытья посуды вручную DISH CLEANER",
    price_1_litre:360,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
  {
    id:13,
    title:"Средство для мытья посудомоечных машин DISH CLEANER AUTOMAT",
    price_1_litre:720,
    inCart_1_litre:false,
    volume_1:"1 литр",
    count_1:0,
    total_1:0,
  },
{
  id:14,
  title:"Средство для мойки фасадов зданий FACADE CLEANER",
  price_1_litre:870,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
  {
  id:15,
  title:"Средство для мытья полов нейтральное эконом FLOOR WASH",
  price_1_litre:640,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:16,
  title:"Средство для мытья полов нейтральное FLOOR WASH+",
  price_1_litre:640,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:17,
  title:"Средство для мытья полов щелочное FLOOR WASH POWER",
  price_1_litre:670,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},

{
  id:18,
  title:"Средство для очистки стекол и зеркал CRYSTAL GLASS",
  price_1_litre:640,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:19,
  title:"Средство для очистки ковровых покрытий и текстиля высокопенное CRYSTAL FOAM CARPET+",
  price_1_litre:820,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:20,
  title:"Средство для очистки духовых шкафов и грилей CRYSTAL GRILL CLEANER",
  price_1_litre:720,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:21,
  title:"Средство по уходу за изделиями из кожи CRYSTAL LEATHER CONDITIONER",
  price_1_litre:1440,
  inCart_1_litre:false,
  volume_0_5:"0.5 литра",
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:22,
  title:"Полироль пластика глянцевая CRYSTAL POLYROL GLOSSY",
  price_1_litre:1440,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:23,
  title:"Полироль пластика матовая CRYSTAL POLYROL MATTE",
  price_1_litre:1440,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:24,
  title:"Полироль пластика матовая CRYSTAL SPOT CLEANER",
  price_1_litre:0,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:25,
  title:"Средство для биотуалетов BIO",
  price_1_litre:0,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
{
  id:26,
  title:"Средство для удаления жира, пищевых нагаров CARBON+",
  price_1_litre:0,
  inCart_1_litre:false,
  volume_1:"1 литр",
  count_1:0,
  total_1:0,
},
];
