export const storeCleaners_0_5 = [

  {
    id:1,
    title:"Средство для чистки сантехники хлорное CH-GEL",
    price_0_5_litre:420,
    inCart_0_5_litre:false,
    volume_0_5:"0.5 литра",
    count_0_5:0,
    total_0_5:0,
  },
  {
    id:2,
    title:"Жидкое мыло AMELI",
    price_0_5_litre:260,
    inCart_0_5_litre:false,
    volume_0_5:"0.5 литра",
    count_0_5:0,
    total_0_5:0,
  },
  {
    id:3,
    title:"Жидкое мыло AMELI+ ",
    price_0_5_litre:280,
    inCart_0_5_litre:false,
    volume_0_5:"0.5 литра",
    count_0_5:0,
    total_0_5:0,
  },
  {
    id:4,
    title:"Жидкое мыло с дезинфецирующим эффектом AMELI DES ",
    price_0_5_litre:304,
    inCart_0_5_litre:false,
    volume_0_5:"0.5 литра",
    count_0_5:0,
    total_0_5:0,
  },
  {
    id:5,
    title:"Жидкое мыло AMELI GLICERIN",
    price_0_5_litre:322,
    inCart_0_5_litre:false,
    volume_0_5:"0.5 литра",
    count_0_5:0,
    total_0_5:0,
  },
  {
    id:6,
    title:"Щелочное средтво для очистки текстиля и ковров CARPET",
    price_0_5_litre:575,
    inCart_0_5_litre:false,
    volume_0_5:"0.5 литра",
    count_0_5:0,
    total_0_5:0,
  },
  {
    id:7,
    title:"Средство для мытья посуды вручную DISH CLEANER",
    price_0_5_litre:290,
    inCart_0_5_litre:false,
    volume_0_5:"0.5 литра",
    count_0_5:0,
    total_0_5:0,
  },
  {
  id:8,
  title:"Средство для мытья полов нейтральное эконом FLOOR WASH",
  price_0_5_litre:420,
  inCart_0_5_litre:false,
  volume_0_5:"0.5 литра",
  count_0_5:0,
  total_0_5:0,
},
{
  id:9,
  title:"Средство для очистки стекол и зеркал CRYSTAL GLASS",
  price_0_5_litre:390,
  inCart_0_5_litre:false,
  volume_0_5:"0.5 литра",
  count_0_5:0,
  total_0_5:0,
},
{
  id:10,
  title:"Средство для очистки ковровых покрытий и текстиля высокопенное CRYSTAL FOAM CARPET+",
  price_0_5_litre:575,
  inCart_0_5_litre:false,
  volume_0_5:"0.5 литра",
  count_0_5:0,
  total_0_5:0,
},
{
  id:11,
  title:"Средство для очистки духовых шкафов и грилей CRYSTAL GRILL CLEANER",
  price_0_5_litre:635,
  inCart_0_5_litre:false,
  volume_0_5:"0.5 литра",
  count_0_5:0,
  total_0_5:0,
},
{
  id:12,
  title:"Средство по уходу за изделиями из кожи CRYSTAL LEATHER CONDITIONER",
  price_0_5_litre:780,
  inCart_0_5_litre:false,
  volume_0_5:"0.5 литра",
  count_0_5:0,
  total_0_5:0,
},
{
  id:13,
  title:"Средство для удаления жира, пищевых нагаров CARBON+",
  price_0_5_litre:0,
  inCart_0_5_litre:false,
  volume_0_5:"0.5 литра",
  count_0_5:0,
  total_0_5:0,
},
];
